import type { MemoryVolume } from "@scelar/nodepod";
import { SharedStore, init } from "@wasmer/sdk";

type Path = string;
/** Reserved Directory-only files for the interactive WASIX session. */
export const WASIX_SESSION_CONTROL_DIR = ".wasix-session";

/** WASI signal numbers the host delivers to a single running command. */
export const SIGINT = 2;
export const SIGKILL = 9;

type SessionConfigWire = {
  root: string;
  sharedSystemPaths: string[];
  /** Same-origin gateway WebSocket the runtime's virtual-net client connects to. */
  networkGatewayUrl?: string;
  /** Transferred MessagePort pairing the worker with an in-page gateway. */
  networkGatewayPort?: MessagePort;
};

const WASIX_SHARED_SYSTEM_PATHS = ["/home", "/tmp"] as const;

export type WasixSessionCapabilities = { pipe: boolean };

export type WasixSessionCommand = {
  packageUrl: string;
  packageSha256: string;
  command: string;
  /** Keep this parsed package until the session worker is terminated. */
  retainPackage?: boolean;
  /** Runs the package entrypoint, needed for a TTY-capable interactive shell. */
  entrypoint?: boolean;
  /** Exact registry package identity when the package needs registry dependencies. */
  registrySpecifier?: string;
  /** Registry packages exposed as commands to a running WASIX process. */
  uses?: string[];
};

export type WasixSessionOptions = {
  volume: MemoryVolume;
  root?: string;
  cols?: number;
  rows?: number;
  /** Same-origin gateway WebSocket for guest TCP/DNS (e.g. `wss://host/net-gateway/`). */
  networkGatewayUrl?: string;
  /** MessagePort (transferred into the worker) for the in-page fetch-based gateway. */
  networkGatewayPort?: MessagePort;
};

export type WasixSessionRunOptions = {
  cwd?: string;
  env?: Record<string, string>;
  stdinBytes?: Uint8Array;
  signal?: AbortSignal;
  onOutput?: (stream: "stdout" | "stderr", chunk: Uint8Array) => void;
  onReady?: (write: (data: Uint8Array) => Promise<void>, end: () => Promise<void>) => void | Promise<void>;
  /** The exec id, so a caller can later signal this command and only this one. */
  onStart?: (execId: number) => void;
};

/**
 * Where an exec's wall time went (SESSION_STALL_PLAN §6).
 *
 * `runMs` covers `command.run`, which resolves and compiles the command's
 * `uses:` packages before instantiating. If it stays large across repeated
 * identical execs, the composed toolset is being recompiled per call and the
 * fix is a session-lifetime package rather than a warmer cache.
 */
export type WasixExecTimings = {
  fetchMs: number;
  loadMs: number;
  /** True when this exec reused the session's retained parsed package. */
  packageCached: boolean;
  runMs: number;
  waitMs: number;
  /** Waiting for the stdout/stderr pumps to finish after the guest exited. */
  drainMs: number;
  /** False when the drain hit its timeout, i.e. the pipes never reached EOF. */
  drained: boolean;
  /** The worker's own total, so `total - execMs` isolates message transport. */
  execMs: number;
};

export type WasixSessionResult = {
  code: number;
  stdout: Uint8Array;
  stderr: Uint8Array;
  /** Absent only if the worker predates the stage timings. */
  timings?: WasixExecTimings;
};

export type WasixInteractiveBash = {
  bashrcPath: string;
  args: string[];
};

type PendingRequest = {
  resolve: (value: any) => void;
  reject: (error: Error) => void;
};

type PendingExec = PendingRequest & {
  stdout: Uint8Array[];
  stderr: Uint8Array[];
  onOutput?: WasixSessionRunOptions["onOutput"];
  onReady?: WasixSessionRunOptions["onReady"];
};

function concatBytes(parts: readonly Uint8Array[]): Uint8Array {
  const size = parts.reduce((total, part) => total + part.byteLength, 0);
  const result = new Uint8Array(size);
  let offset = 0;
  for (const part of parts) {
    result.set(part, offset);
    offset += part.byteLength;
  }
  return result;
}

function workerError(error: { name: string; message: string; stack?: string }): Error {
  const result = new Error(error.message);
  result.name = error.name;
  if (error.stack) result.stack = error.stack;
  return result;
}

/** POSIX single-quoting: the only quoting that needs no escape table. */
function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

function normalizeRoot(value: string): string {
  if (!value.startsWith("/") || value.includes("\0")) throw new Error("WASIX session root must be an absolute path");
  if (value === "/") return value;
  const parts = value.split("/");
  if (parts.some((part, index) => index > 0 && (part === "" || part === "." || part === ".."))) {
    throw new Error(`Invalid WASIX session root ${JSON.stringify(value)}`);
  }
  return value;
}

function osc133BashRc(root: string): string {
  return [
    "# Generated by Riff; OSC 133 marks prompt and command boundaries.",
    "# wasmer/bash@1.0.25 hangs on a bare interactive $(true); : uses the same no-op implementation.",
    "alias true=:",
    // Probe P10: the `cwd` passed to `command.run` sets $PWD and the working
    // directory that spawned children inherit, but it never becomes Bash's own
    // relative-path resolution base -- that stays at `/` until Bash issues a
    // real chdir. Without this line `echo x > file` silently creates `/file`
    // outside the mounted workspace. Children were unaffected, which is why
    // this survived the original session implementation.
    `cd ${shellSingleQuote(root)}`,
    "__riff_osc133() { printf '\\033]133;%s\\007' \"$1\"; }",
    "PS0='\\[\\033]133;C\\007\\]'",
    "PROMPT_COMMAND='__riff_osc133 \"D;$?\"'",
    "PS1='\\[\\033]133;A\\007\\]\\u@\\h:\\w\\$ \\[\\033]133;B\\007\\]'",
    "",
  ].join("\n");
}

function sharedStoreBytes(volume: MemoryVolume): number {
  let dataBlocks = 1;
  let entries = 0;
  const walk = (directory: string): void => {
    for (const name of volume.readdirSync(directory)) {
      const path = directory === "/" ? `/${name}` : `${directory}/${name}`;
      const stat = volume.lstatSync(path);
      entries += 1;
      if (stat.isDirectory() && !stat.isSymbolicLink()) {
        dataBlocks += 1;
        walk(path);
      } else {
        dataBlocks += stat.isFile() ? Math.max(1, Math.ceil(stat.size / 4096)) : 1;
      }
    }
  };
  walk("/");
  // Params::for_region provisions one inode per two data blocks. Account for
  // both constraints, directory growth/pointer blocks, and future writes.
  const requiredBlocks = Math.max(dataBlocks, (entries + 1) * 2);
  const estimate = Math.max(
    512 * 1024 * 1024,
    Math.ceil((requiredBlocks * 4224 + 128 * 1024 * 1024) * 2),
  );
  const rounded = Math.ceil(estimate / 65536) * 65536;
  if (rounded >= 0xffff0000) throw new Error("Workspace is too large for the WASIX shared store");
  return rounded;
}

type SharedStoreAttachment = {
  store: SharedStore;
  memory: WebAssembly.Memory;
};

const sharedStoreAttachments = new WeakMap<MemoryVolume, Promise<SharedStoreAttachment>>();
const sharedSessions = new WeakMap<MemoryVolume, Promise<WasixSession>>();

async function sharedStoreForVolume(volume: MemoryVolume): Promise<SharedStoreAttachment> {
  const existing = sharedStoreAttachments.get(volume);
  if (existing) return existing;

  const pending = (async () => {
    const attachable = volume as MemoryVolume & {
      attachSharedStore(store: SharedStore): void;
    };
    if (typeof attachable.attachSharedStore !== "function") {
      throw new Error("Installed Nodepod does not support the shared-store backend");
    }
    const initialized = await init();
    const store = SharedStore.create(sharedStoreBytes(volume));
    try {
      attachable.attachSharedStore(store);
    } catch (error) {
      store.free();
      throw error;
    }
    return { store, memory: initialized.memory };
  })();
  sharedStoreAttachments.set(volume, pending);
  try {
    return await pending;
  } catch (error) {
    if (sharedStoreAttachments.get(volume) === pending) sharedStoreAttachments.delete(volume);
    throw error;
  }
}

/** A persistent WASIX runtime attached to Nodepod's shared filesystem store. */
export class WasixSession {
  private readonly store: SharedStore;
  private readonly memory: WebAssembly.Memory;
  private readonly rootPath: string;
  private worker: Worker;
  private nextId = 1;
  private readonly requests = new Map<number, PendingRequest>();
  private readonly execs = new Map<number, PendingExec>();
  private readonly stdinAcks = new Map<number, PendingRequest>();
  private disposed = false;
  private leases = 1;
  private cols: number;
  private rows: number;
  capabilities: WasixSessionCapabilities;

  private constructor(
    options: WasixSessionOptions,
    store: SharedStore,
    memory: WebAssembly.Memory,
    worker: Worker,
    root: string,
    capabilities: WasixSessionCapabilities,
  ) {
    this.store = store;
    this.memory = memory;
    this.worker = worker;
    this.rootPath = root;
    this.capabilities = capabilities;
    this.cols = options.cols ?? 80;
    this.rows = options.rows ?? 24;
    this.bindWorker(worker);
  }

  static async open(options: WasixSessionOptions): Promise<WasixSession> {
    const existing = sharedSessions.get(options.volume);
    if (existing) {
      const session = await existing;
      session.acquire(options);
      return session;
    }

    const pending = WasixSession.openNew(options);
    sharedSessions.set(options.volume, pending);
    try {
      const session = await pending;
      const disposable = options.volume as MemoryVolume & { onDispose?: (listener: () => void) => () => void };
      disposable.onDispose?.(() => session.shutdown());
      return session;
    } catch (error) {
      if (sharedSessions.get(options.volume) === pending) sharedSessions.delete(options.volume);
      throw error;
    }
  }

  private static async openNew(options: WasixSessionOptions): Promise<WasixSession> {
    const root = normalizeRoot(options.root ?? "/work/repo");
    const sharedSystemPaths = WASIX_SHARED_SYSTEM_PATHS.map(normalizeRoot);
    for (const path of sharedSystemPaths) options.volume.mkdirSync(path, { recursive: true });
    options.volume.mkdirSync("/home/user", { recursive: true });
    const { store, memory } = await sharedStoreForVolume(options.volume);
    const worker = new Worker(new URL("./wasixSessionWorker.ts", import.meta.url), { type: "module" });
    try {
      const opened = await WasixSession.openWorker(
        worker,
        { root, sharedSystemPaths, networkGatewayUrl: options.networkGatewayUrl, networkGatewayPort: options.networkGatewayPort },
        memory,
        store.pointer,
        store.byteLength,
        options.cols,
        options.rows,
      );
      const session = new WasixSession(
        options,
        store,
        memory,
        worker,
        root,
        opened.capabilities,
      );
      session.nextId = 2;
      return session;
    } catch (error) {
      worker.terminate();
      throw error;
    }
  }

  private acquire(options: WasixSessionOptions): void {
    const root = normalizeRoot(options.root ?? "/work/repo");
    if (root !== this.rootPath) {
      throw new Error(`The shared WASIX session is rooted at ${JSON.stringify(this.rootPath)}, not ${JSON.stringify(root)}`);
    }
    if (this.disposed) throw new Error("WASIX session is closed");
    this.leases++;
    if (options.cols !== undefined && options.rows !== undefined) this.resize(options.cols, options.rows);
  }

  get root(): string {
    return this.rootPath;
  }

  /** Install the bashrc that emits OSC 133 command-boundary markers. */
  async installInteractiveBash(): Promise<WasixInteractiveBash> {
    const path = `${WASIX_SESSION_CONTROL_DIR}/bashrc`;
    await this.writeControlFile(path, new TextEncoder().encode(osc133BashRc(this.rootPath)));
    const bashrcPath = `${this.rootPath}/${path}`;
    return {
      bashrcPath,
      args: ["--noprofile", "--rcfile", bashrcPath, "-i"],
    };
  }

  /**
   * Read the next chunk from the shared request pipe (blocks until a guest
   * stub writes a request). Returns an empty `Uint8Array` on EOF.
   */
  async bridgeRead(): Promise<Uint8Array> {
    const value = await this.request("bridge-read", {}, []);
    return value instanceof Uint8Array ? value : new Uint8Array();
  }

  /** Write a chunk into the shared request pipe (guest-readable). */
  async bridgeWrite(data: Uint8Array): Promise<void> {
    const copy = data.slice().buffer;
    await this.request("bridge-write", { data: copy }, [copy]);
  }

  /**
   * Plant a response pipe so the guest stub with that pid, running under that
   * channel, can open it. Safe to call repeatedly; returns the same pipe.
   */
  async bridgeOpenResp(channel: string, pid: number): Promise<void> {
    await this.request("bridge-resp-open", { channel, pid }, []);
  }

  /** Write a chunk into the response pipe for a specific channel and pid. */
  async bridgeWriteTo(channel: string, pid: number, data: Uint8Array): Promise<void> {
    const copy = data.slice().buffer;
    await this.request("bridge-resp-write", { channel, pid, data: copy }, [copy]);
  }

  /**
   * The guest `RIFF_BRIDGE_ROOT` for one exec, and the Directory-root
   * directory its response pipes live in.
   *
   * The stub derives its private response pipe as
   * `$RIFF_BRIDGE_ROOT/.wasix-session/bridge/$pid`, and pids repeat across
   * top-level instances, so the root is what makes the path unique per
   * command. It stays under the session control directory.
   */
  static bridgeChannel(root: string, execId: number): { guestRoot: string; channel: string } {
    const suffix = `${WASIX_SESSION_CONTROL_DIR}/c/${execId}`;
    return {
      guestRoot: `${root}/${suffix}`,
      channel: `/${suffix}/${WASIX_SESSION_CONTROL_DIR}/bridge`,
    };
  }

  /** Map a guest `RIFF_BRIDGE_ROOT` back to its Directory-root channel dir. */
  channelForBridgeRoot(guestRoot: string | undefined): string {
    const fallback = `/${WASIX_SESSION_CONTROL_DIR}/bridge`;
    if (guestRoot === undefined) return fallback;
    const prefix = `${this.rootPath}/`;
    if (!guestRoot.startsWith(prefix)) return fallback;
    return `/${guestRoot.slice(prefix.length)}/${WASIX_SESSION_CONTROL_DIR}/bridge`;
  }

  /**
   * Install WASIX bridge stub binaries into the control directory and return
   * the environment the interactive bash needs to reach them and the pipe.
   */
  async installBridge(stubs: ReadonlyMap<string, Uint8Array>): Promise<{
    pipeEnv: Record<string, string>;
    pathEntry: string;
  }> {
    const bin = `${WASIX_SESSION_CONTROL_DIR}/bin`;
    for (const [name, bytes] of stubs) {
      await this.writeControlFile(`${bin}/${name}`, bytes);
    }
    return {
      pipeEnv: {
        RIFF_BRIDGE_PIPE: `${this.rootPath}/${WASIX_SESSION_CONTROL_DIR}/bridge/req`,
        RIFF_BRIDGE_ROOT: this.rootPath,
      },
      pathEntry: `${this.rootPath}/${bin}`,
    };
  }

  /**
   * Install guest-executed binaries (not bridge stubs) into the same control
   * `bin` directory, so they win PATH lookup ahead of the composed packages.
   * Used for multicall payloads whose dispatch keys off `argv[0]` basename.
   */
  async installBinaries(binaries: ReadonlyMap<string, Uint8Array>): Promise<void> {
    const bin = `${WASIX_SESSION_CONTROL_DIR}/bin`;
    for (const [name, bytes] of binaries) {
      await this.writeControlFile(`${bin}/${name}`, bytes);
    }
  }

  /**
   * Install a file under the session control directory at a caller-chosen
   * path (relative to the control dir). Used for non-executable session
   * payloads such as the gateway CA bundle.
   */
  async installSessionFile(path: string, data: Uint8Array): Promise<void> {
    await this.writeControlFile(`${WASIX_SESSION_CONTROL_DIR}/${path.replace(/^\/+/, "")}`, data);
  }

  async run(command: WasixSessionCommand, args: readonly string[], options: WasixSessionRunOptions = {}): Promise<WasixSessionResult> {
    this.assertOpen();
    if (options.signal?.aborted) throw new DOMException("Command aborted", "AbortError");
    if (!/^[0-9a-f]{64}$/.test(command.packageSha256)) {
      throw new Error("WASIX session command has an invalid SHA-256");
    }
    if (command.registrySpecifier !== undefined && !/^[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*@\d+\.\d+\.\d+$/.test(command.registrySpecifier)) {
      throw new Error("WASIX session command has an invalid exact registry specifier");
    }
    if (command.uses?.some((specifier) => !/^[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9-]*@\d+\.\d+\.\d+$/.test(specifier))) {
      throw new Error("WASIX session command has an invalid exact use specifier");
    }
    const id = this.nextId++;
    const stdin = options.stdinBytes?.slice().buffer;
    const transfer = stdin === undefined ? [] : [stdin];
    // Each command gets its own bridge channel: guest pids repeat across
    // top-level instances, so the channel is what keeps two concurrent stubs
    // off the same response pipe.
    const { guestRoot } = WasixSession.bridgeChannel(this.rootPath, id);
    return new Promise<WasixSessionResult>((resolve, reject) => {
      // Abort this command only. This used to call failSession, which
      // terminates the worker: one Bash-tool timeout would have killed every
      // other command in the session, including a backgrounded dev server.
      const abort = () => this.interruptExec(id, SIGKILL);
      options.signal?.addEventListener("abort", abort, { once: true });
      this.execs.set(id, {
        stdout: [],
        stderr: [],
        onOutput: options.onOutput,
        onReady: options.onReady,
        resolve: (value) => {
          options.signal?.removeEventListener("abort", abort);
          resolve(value as WasixSessionResult);
        },
        reject: (error) => {
          options.signal?.removeEventListener("abort", abort);
          reject(error);
        },
      });
      this.worker.postMessage({
        id,
        kind: "exec",
        command,
        args: [...args],
        cwd: options.cwd ?? this.rootPath,
        env: { ...(options.env ?? {}), RIFF_BRIDGE_ROOT: guestRoot },
        stdinBytes: stdin,
        liveStdin: options.onReady !== undefined,
      }, transfer);
      options.onStart?.(id);
    });
  }

  /**
   * Deliver a signal to one running command, leaving the rest of the session
   * alone. 2 = SIGINT (what Ctrl-C on the foreground command means), 9 =
   * SIGKILL (a tool-call timeout).
   */
  interruptExec(execId: number, signal: number = SIGINT): void {
    if (this.disposed) return;
    if (!this.execs.has(execId)) return;
    this.worker.postMessage({ kind: "signal", execId, signal });
  }

  /** Signal this exec's foreground process and return its guest pid. */
  async interruptForeground(execId: number, signal: number = SIGINT): Promise<number | null> {
    if (this.disposed || !this.execs.has(execId)) return null;
    const result = await this.request("signal-foreground", { execId, signal }) as { pid: number | null };
    return result.pid;
  }

  resize(cols: number, rows: number): void {
    this.assertOpen();
    if (!Number.isInteger(cols) || cols <= 0 || !Number.isInteger(rows) || rows <= 0) return;
    this.cols = cols;
    this.rows = rows;
    this.worker.postMessage({ kind: "resize", cols, rows });
  }

  async dispose(): Promise<void> {
    if (this.disposed) return;
    this.leases = Math.max(0, this.leases - 1);
    if (this.leases > 0) return;
    for (const execId of this.execs.keys()) this.interruptExec(execId, SIGKILL);
  }

  private shutdown(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.worker.terminate();
    this.rejectPending(new Error("WASIX session closed"));
  }

  private async writeControlFile(path: Path, data: Uint8Array): Promise<void> {
    this.assertOpen();
    const parts = path.split("/");
    if (parts.some((part) => part === "" || part === "." || part === ".." || part.includes("\0"))) {
      throw new Error(`Invalid WASIX control path ${JSON.stringify(path)}`);
    }
    if (path !== WASIX_SESSION_CONTROL_DIR && !path.startsWith(`${WASIX_SESSION_CONTROL_DIR}/`)) {
      throw new Error(`WASIX control files must be under ${WASIX_SESSION_CONTROL_DIR}/`);
    }
    const absolute = this.rootPath === "/" ? `/${path}` : `${this.rootPath}/${path}`;
    this.store.mkdir(absolute.slice(0, absolute.lastIndexOf("/")), true, 0o755);
    this.store.writeFile(absolute, data);
  }

  private request(kind: "bridge-read" | "bridge-write" | "bridge-resp-open" | "bridge-resp-write" | "signal-foreground", data: Record<string, unknown>, transfer: Transferable[] = []): Promise<unknown> {
    this.assertOpen();
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      this.requests.set(id, { resolve, reject });
      this.worker.postMessage({ id, kind, ...data }, transfer);
    });
  }

  private bindWorker(worker: Worker): void {
    worker.onmessage = (event) => this.onMessage(event.data);
    worker.onerror = (event) => {
      // A worker `ErrorEvent` carries the only location information available
      // for a fault inside the session worker, and `message` alone is usually
      // too vague to act on. Fold it into the error so it reaches the caller's
      // reporting path rather than only the console.
      const origin = event.filename ? ` (${event.filename}:${event.lineno}:${event.colno})` : "";
      this.failSession(new Error(`WASIX session worker failed: ${event.message}${origin}`));
    };
  }

  private static openWorker(
    worker: Worker,
    config: SessionConfigWire,
    memory: WebAssembly.Memory,
    storePointer: number,
    storeBytes: number,
    cols?: number,
    rows?: number,
  ): Promise<{ capabilities: WasixSessionCapabilities }> {
    return new Promise((resolve, reject) => {
      const id = 1;
      const timeout = setTimeout(() => reject(new Error("Timed out opening WASIX session")), 60_000);
      worker.onmessage = (event) => {
        const message = event.data;
        if (message.id !== id) return;
        clearTimeout(timeout);
        if (message.kind === "opened") resolve(message);
        else reject(message.kind === "error" ? workerError(message.error) : new Error("Invalid WASIX session open reply"));
      };
      worker.onerror = (event) => {
        clearTimeout(timeout);
        reject(new Error(event.message));
      };
      // A MessagePort is only usable after being transferred (not cloned),
      // so the gateway port must appear in the transfer list.
      const transfer: Transferable[] = config.networkGatewayPort !== undefined ? [config.networkGatewayPort] : [];
      worker.postMessage({ id, kind: "open-session", config, memory, storePointer, storeBytes, cols, rows }, transfer);
    });
  }

  private onMessage(message: any): void {
    if (message.kind === "output") {
      const exec = this.execs.get(message.id);
      if (exec === undefined) return;
      const chunk = new Uint8Array(message.data);
      (message.stream === "stdout" ? exec.stdout : exec.stderr).push(chunk);
      exec.onOutput?.(message.stream, chunk);
      return;
    }
    if (message.kind === "ready") {
      const exec = this.execs.get(message.id);
      if (exec === undefined) return;
      void exec.onReady?.(
        (data) => this.stdin(message.id, "stdin-write", data),
        () => this.stdin(message.id, "stdin-end"),
      );
      return;
    }
    if (message.kind === "stdin-ack") {
      const pending = this.stdinAcks.get(message.id);
      if (pending === undefined) return;
      this.stdinAcks.delete(message.id);
      if (message.ok) pending.resolve(undefined);
      else pending.reject(new Error(message.error));
      return;
    }
    if (message.kind === "exit") {
      const exec = this.execs.get(message.id);
      if (exec === undefined) return;
      this.execs.delete(message.id);
      exec.resolve({
        code: message.code,
        stdout: concatBytes(exec.stdout),
        stderr: concatBytes(exec.stderr),
        timings: message.timings,
      });
      return;
    }
    if (message.kind === "error") {
      const error = workerError(message.error);
      const exec = this.execs.get(message.id);
      if (exec !== undefined) {
        this.execs.delete(message.id);
        exec.reject(error);
        return;
      }
      const request = this.requests.get(message.id);
      if (request !== undefined) {
        this.requests.delete(message.id);
        request.reject(error);
      }
      return;
    }
    const request = this.requests.get(message.id);
    if (request === undefined) return;
    this.requests.delete(message.id);
    if (message.kind === "foreground-signalled") request.resolve(message);
    else if (message.kind === "bridge-frame") request.resolve(new Uint8Array(message.data));
    else request.resolve(undefined);
  }

  private stdin(id: number, kind: "stdin-write" | "stdin-end", data?: Uint8Array): Promise<void> {
    return new Promise((resolve, reject) => {
      this.stdinAcks.set(id, { resolve, reject });
      if (kind === "stdin-write") {
        const copy = data!.slice().buffer;
        this.worker.postMessage({ id, kind, data: copy }, [copy]);
      } else {
        this.worker.postMessage({ id, kind });
      }
    });
  }

  private assertOpen(): void {
    if (this.disposed) throw new Error("WASIX session is closed");
  }

  private failSession(error: Error): void {
    if (this.disposed) return;
    this.disposed = true;
    this.worker.terminate();
    this.rejectPending(error);
  }

  private rejectPending(error: Error): void {
    for (const request of this.requests.values()) request.reject(error);
    this.requests.clear();
    for (const exec of this.execs.values()) exec.reject(error);
    this.execs.clear();
    for (const stdin of this.stdinAcks.values()) stdin.reject(error);
    this.stdinAcks.clear();
  }
}
